export const LOAN_API_ENDPOINTS = {
    LOAN: "attachments",
    CASH_IN_OUT: "analytics",
    SUPERADMIN: "attributes",
    TENANT: "attribute-values",
    SUPERADMIN_ANALYTICS: "superadmin/analytics",
    SUPERADMIN_COMPANIES: "superadmin/companies",
    SUPERADMIN_COMPANIES_ACTIVE_LIST:"superadmin/companies/active/list",
    SUPERADMIN_ADMINS: "superadmin/admins",
    SUPERADMIN_PAYMENT_GATEWAYS: "superadmin/payment_gateways",
    SUPERADMIN_PAYMENT_GATEWAYS_SEARCH: "superadmin/payment_gateways/search",
    SUPERADMIN_PAYMENT_GATEWAYS_VIEW_SINGLE: "superadmin/payment_gateways/view/single",
    SUPERADMIN_PAYMENT_GATEWAYS_VIEW: "superadmin/payment_gateways/view",
    SUPERADMIN_PAYMENT_GATEWAYS_CREATE: "superadmin/payment_gateways/create",
    SUPERADMIN_PAYMENT_GATEWAYS_UPDATE: "superadmin/payment_gateways/update",
    SUPERADMIN_PAYMENT_GATEWAYS_DELETE: "superadmin/payment_gateways/delete",
    SUPERADMIN_PAYMENT_GATEWAYS_ACTIVE_LIST:"superadmin/payment_gateways/active/list",
    SUPERADMIN_ADMINS_CREATE: "superadmin/admins/create",
    SUPERADMIN_ADMINS_UPDATE: "superadmin/admins/update",
    SUPERADMIN_ADMINS_DELETE: "superadmin/admin/delete",
    SUPERADMIN_ADMINS_VIEW: "superadmin/admins/view",
    SUPERADMIN_ADMINS_SEARCH: "superadmin/admins/search",
    SUPERADMIN_ADMINS_VIEW_SINGLE: "superadmin/admins/view/single",
    SUPERADMIN_COMPANIES_VIEW: "superadmin/companies/view",
    SUPERADMIN_COMPANIES_SEARCH: "superadmin/companies/search",
    SUPERADMIN_COMPANIES_CREATE: "superadmin/companies/create",
    SUPERADMIN_COMPANIES_UPDATE: "superadmin/companies/update",
    SUPERADMIN_COMPANIES_DELETE: "superadmin/companies/delete",
    SUPERADMIN_COMPANIES_VIEW_SINGLE: "superadmin/companies/view/single",
    TENANT_EMPLOYEES_VIEW: "tenant/employees/view",
    TENANT_EMPLOYEES_VIEW_SINGLE: "tenant/employees/view/single",
    TENANT_EMPLOYEES_SEARCH: "tenant/employees/search",
    TENANT_EMPLOYEES_CREATE: "tenant/employees/create",
    TENANT_EMPLOYEES_UPDATE: "tenant/employees/update",
    TENANT_EMPLOYEES_DELETE: "tenant/employees/delete",
    TENANT_CUSTOMERS_VIEW:"tenant/customers/view",
    TENANT_CUSTOMERS_ACTIVE_LIST:"tenant/customers/active/list",
    TENANT_CUSTOMERS_VIEW_SINGLE:"tenant/customers/view/single",
    TENANT_CUSTOMERS_SEARCH:"tenant/customers/search",
    TENANT_CUSTOMERS_CREATE: "tenant/customers/create",
    TENANT_CUSTOMERS_UPDATE: "tenant/customers/update",
    TENANT_CUSTOMERS_DELETE:"tenant/customers/delete",
    TENANT_PAYMENT_ACCOUNTS_VIEW: "tenant/payment_accounts/view",
    TENANT_PAYMENT_ACCOUNTS_VIEW_SINGLE:"tenant/payment_accounts/view/single",
    TENANT_PAYMENT_ACCOUNTS_SEARCH: "tenant/payment_accounts/search",
    TENANT_PAYMENT_ACCOUNTS_CREATE:"tenant/payment_accounts/create",
    TENANT_PAYMENT_ACCOUNTS_UPDATE:"tenant/payment_accounts/update",
    TENANT_PAYMENT_ACCOUNTS_DELETE:"tenant/payment_accounts/delete",
    TENANT_PAYMENT_ACCOUNTS_ACTIVE_LIST:"tenant/payment_accounts/active/list/filter",
    TENANT_SHIFTS_VIEW:"tenant/shifts/view",
    TENANT_SHIFTS_VIEW_SINGLE:"tenant/shifts/view/single",
    TENANT_SHIFTS_SEARCH:"tenant/shifts/search",
    TENANT_SHIFTS_CREATE:"tenant/shifts/create",
    TENANT_SHIFTS_UPDATE:"tenant/shifts/update",
    TENANT_SHIFTS_DELETE:"tenant/shifts/delete",
    TENANT_SHIFTS_ACTIVE_LIST:"tenant/shifts/active/list",
    EMPLOYEE_LOAN_ISSUED_VIEW:"loans/loan_issue/view",
    EMPLOYEE_LOAN_ISSUED_VIEW_SINGLE:"loans/loan_issue/view/single",
    EMPLOYEE_LOAN_ISSUED_SEARCH:"loans/loan_issue/search",
    EMPLOYEE_LOAN_ISSUED_CREATE:"loans/loan_issue/create",
    EMPLOYEE_LOAN_ISSUED_UPDATE:"loans/loan_issue/update",
    EMPLOYEE_LOAN_ISSUED_DELETE:"loans/loan_paid/delete",
    EMPLOYEE_LOAN_DUE:"loans/loan/balance",
    TENANT_LOAN_ISSUED_ACTIVE_LIST: "loans/loan_issue/active/list",
    EMPLOYEE_LOAN_PAID_VIEW:"loans/loan_paid/view",
    EMPLOYEE_LOAN_BALANCE_BY_CUSTOMER_ID: "loans/loan/balance",
    EMPLOYEE_LOAN_PAID_VIEW_SINGLE:"loans/loan_paid/view/single",
    EMPLOYEE_LOAN_PAID_SEARCH:"loans/loan_paid/search",
    EMPLOYEE_LOAN_PAID_CREATE:"loans/loan_paid/create",
    EMPLOYEE_LOAN_PAID_UPDATE:"loans/loan_paid/update",
    EMPLOYEE_LOAN_PAID_DELETE:"loans/loan_paid/delete",
    EMPLOYEE_CASH_IN_VIEW:"cashinouts/cash_in/view",
    EMPLOYEE_CASH_IN_VIEW_SINGLE:"cashinouts/cash_in/view/single",
    EMPLOYEE_CASH_IN_SEARCH:"cashinouts/cash_in/search",
    EMPLOYEE_CASH_IN_CREATE:"cashinouts/cash_in/create",
    EMPLOYEE_CASH_IN_UPDATE:"cashinouts/cash_in/update",
    EMPLOYEE_CASH_IN_DELETE:"cashinouts/cash_in/delete",

    EMPLOYEE_CASH_OUT_VIEW:"cashinouts/cash_out/view",
    EMPLOYEE_CASH_OUT_VIEW_SINGLE:"cashinouts/cash_out/view/single",
    EMPLOYEE_CASH_OUT_SEARCH:"cashinouts/cash_out/search",
    EMPLOYEE_CASH_OUT_CREATE:"cashinouts/cash_out/create",
    EMPLOYEE_CASH_OUT_UPDATE:"cashinouts/cash_out/update",
    EMPLOYEE_CASH_OUT_DELETE:"cashinouts/cash_out/delete",

    EMPLOYEE_CLOCK_IN_VIEW:"clockinouts/clock_in/view",
    EMPLOYEE_CLOCK_IN_VIEW_SINGLE:"clockinouts/clock_in/view/single",
    EMPLOYEE_CLOCK_IN_SEARCH:"clockinouts/clock_in/search",
    EMPLOYEE_CLOCK_IN_CREATE:"clockinouts/clock_in/create",
    EMPLOYEE_CLOCK_IN_UPDATE:"clockinouts/clock_in/update",
    EMPLOYEE_CLOCK_IN_DELETE:"clockinouts/clock_in/delete",
    EMPLOYEE_CLOCK_OUT_VIEW:"clockinouts/clock_out/view",
    EMPLOYEE_CLOCK_OUT_VIEW_SINGLE:"clockinouts/clock_out/view/single",
    EMPLOYEE_CLOCK_OUT_SEARCH:"clockinouts/clock_out/search",
    EMPLOYEE_CLOCK_OUT_CREATE:"clockinouts/clock_out/create",
    EMPLOYEE_CLOCK_OUT_UPDATE:"clockinouts/clock_out/update",
    EMPLOYEE_CLOCK_OUT_DELETE:"clockinouts/clock_out/delete",
    TENANT_ANALYTICS: "tenant/analytics",
    EMPLOYEE_ANALYTICS: "loan/analytics",
    RECENT_ADMINS: "superadmin/recent_admins",
    RECENT_PAYMENT_GATEWAYS: "superadmin/recent_payment_gateways",

    RECENT_EMPLOYEES : "tenant/employees/recent_employees",
    RECENT_CUSTOMERS : "tenant/empolyees/recent_customers",
    RECENT_PAYMENT_ACCOUNTS: "tenant/employees/recent_payment_accounts",
    RECENT_SHIFTS: "tenant/shifts/recent_shifts",

    RECENT_LOAN_ISSUED: "loan/loans/recent_loan_issues",
    RECENT_LOAN_PAID: "loan/loans/recent_loan_paid",
    RECENT_CASH_INS: "cashinout/cashins/recent_cash_ins",
    RECENT_CASH_OUTS:"cashinout/cashouts/recent_cash_outs",
    RECENT_CLOCK_INS: "clockinout/clockins/recent_clock_ins",
    RECENT_CLOCK_OUTS:"clockinout/clockouts/recent_clock_outs",

    ORDERS: "orders",
    USERS: "users",
    REGISTER: "register",
    PRODUCTS: "products",
    POPULAR_PRODUCTS: "popular-products",
    COUPONS: "coupons",
    CUSTOMERS: "customers",
    TAXES: "taxes",
    SHIPPINGS: "shippings",
    SETTINGS: "settings",
    CATEGORIES: "categories",
    TAGS: "tags",
    TYPES: "types",
    PROFILE_UPDATE: "profile-update",
    LOGOUT: "logout",
    ME: "me",
    TOKEN: "token",
    BLOCK_USER: "users/block-user",
    UNBLOCK_USER: "users/unblock-user",
    CHANGE_PASSWORD: "change-password",
    FORGET_PASSWORD: "forget-password",
    VERIFY_FORGET_PASSWORD_TOKEN: "verify-forget-password-token",
    RESET_PASSWORD: "reset-password",
    DOWNLOAD_INVOICE: "download/invoice",
    APPROVE_SHOP: "approve-shop",
    DISAPPROVE_SHOP: "disapprove-shop",
    SHOPS: "shops",
    MY_SHOPS: "my-shops",
    WITHDRAWS: "withdraws",
    APPROVE_WITHDRAW: "approve-withdraw",
    ADD_WALLET_POINTS: "add-points",
    REFUNDS: "refunds",
    STAFFS: "staffs",
    ADD_STAFF: "staffs",
    REMOVE_STAFF: "staffs",
    IMPORT_PRODUCTS: "import-products/",
    IMPORT_ATTRIBUTES: "import-attributes/",
    IMPORT_VARIATION_OPTIONS: "import-variation-options/",
  };
  